apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devspaces-vibe-coding-ws
  labels:
    app.kubernetes.io/part-of: devspaces-vibe-coding
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
